### ISSUE TITLE
Deprecated API `open_file/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java uses or overrides a deprecated API.`

### ISSUE THREAD

**Issue by nilsreichardt** [crazecoder/open_file#249]
## Steps to reproduce

1. Clone this repository
2. Navigate to the `example`
3. Run `flutter run` for an Android device

## Logs

```
Launching lib/main.dart on sdk gphone arm64 in debug mode...
main.dart:1
Note: /Users/nils/Projects/open_file/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:51819/sSIVwYAFg90=/ws
```

## Context

Used commit: f19c0363cb9c73f9aa8d76a392d9981c8883491f

**Comment by hassanmugl** [comment]
same problem

**Comment by TuyulTronik** [comment]
me too

**Comment by dorklein** [comment]
same

**Comment by buraktahap** [comment]
same here

**Comment by yemreeee** [comment]
exactly

**Comment by mooosamir** [comment]
me too 
Has anyone reached the solution?

**Comment by crazecoder** [comment]
```java
PackageManager.queryIntentActivities(Intent intent, int flags)
```
This method is deprecated on API 33 , I will add a conditional judgment

**Comment by kauzige** [comment]
Same error here in Flutter 3.22.1

With the build.gradle :

```
compileSdkVersion 34
    buildToolsVersion("30.0.3")
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    
    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 31
    }
```

**Comment by Falchizao** [comment]
did someone solve this problem? Same error here
```

.pub-cache/hosted/pub.dev/open_file-3.3.2/android/src/main/java/com/crazecoder/openfile/OpenFilePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.
```

**Comment by Milouneuse** [comment]
It seems like the bug is back

**Comment by kauzige** [comment]
> Same error here in Flutter 3.22.1
> 
> open_file: ^3.2.1
> 
> With the build.gradle :
> 
> ```
> compileSdkVersion 34
>     buildToolsVersion("30.0.3")
>     ndkVersion flutter.ndkVersion
> 
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
>     
>     defaultConfig {
>         minSdkVersion 24
>         targetSdkVersion 31
>     }
> ```
> 
> error
> 
> ```
> AppData\Local\Pub\Cache\hosted\pub.dev\open_file-3.3.2\android\src\main\java\com\crazecoder\openfile\OpenFilePlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':package_info_plus:compileDebugJavaWithJavac'.
> ```

I fixed, but i had to download the JDK 17, I had a lot of errors so i uninstalled Android Studio and reinstalled with the already JDK version

**Comment by crazecoder** [comment]
If new versions still have this bug, upgrade your compileSdk to 34
